config {
  type: "table",
  schema: 'internacional',
  name:'mktflow_base_logadofree_internacional',
  tags: ['schedule_tag=internacional_mktflow_base_logadofree_internacional.',
         'schedule_cron=0 12 * * *'],
   bigquery: {
        labels: {
            schedule: "diario",
            tags: "internacional",
            owner: "martech",
            mktcloud: "true"
    }
}}

SELECT globo_id, 
oferta_consumo as regiao
FROM ${ref(`internacional`,`base_lf_internacional`)}