config {
    type: 'table',
    tags: ['schedule_tag=globoorg_mkt_mktflow_base_retro_home_2024'],
    name: 'mktflow_base_retro_home_2024',
    schema: 'globoorg_mkt',
    description: ''
}

SELECT distinct globoid AS globo_id
, globoid_hash
FROM --`gglobo-mkt-ins-hdg-prd.retrospectiva.retrospectiva_2024_vf`
${ref("retrospectiva", "retrospectiva_2024_vf")}
WHERE primeiroProduto = "globo.com" 