config {
  type: "table",
  name: "mktflow_novidades_v3",
  schema: "jornadas_mkt",
tags: ["novidades",
        'schedule_tag=jornadas_mkt_mktflow_novidades_v3',
        'schedule_cron=0 10 * * *'
        ], 

  bigquery: {
    labels: {
      tags: "novidades",
      owner: "martech",
       mktcloud: "true"
        }
    }
}

SELECT
*
FROM 
${ref('conteudo', 'novidades_v3')}