config {
    type: 'table',
    tags: ['schedule_tag=segment_api_permutive_ge_bottom1'],
    name: 'permutive_ge_bottom1',
    schema: 'segment_api',
    description: 'base de globoids para teste de intereção com bottom1 mensal oferta no ge',
    columns: {}
}

SELECT
  DISTINCT globo_id AS user_id
FROM ${ref("segmento_ge", "ge_bottom1")}
--`gglobo-mkt-ins-hdg-prd.segmento_ge.ge_bottom1`