config {
  type: 'table',
  name: 'inatividade_por_produto',
  schema: 'atualizacao_tabelas',
  tags: ['atualizacao_tabelas', 
         'atualizacao_tabelas_2', 
         'schedule_tag=atualizacao_tabelas_inatividade_por_produto',
 "schedule_cron=0 10,13 * * *"],
  description: '',
  columns: {}
}

SELECT
  inativo,
  Produto_Contratado,
  id_asset
from
  ${ref('usuarios', 'perfil_assinantes_ativo_reduzido')}
