config {
  type: "table",
  schema: 'atualizacao_tabelas',
  name: 'titulares_e_dependentes',
  tags: ['atualizacao_tabelas', 
         'atualizacao_tabelas_2', 
         'schedule_tag=atualizacao_tabelas_titulares_e_dependentes',
 "schedule_cron=0 10,13 * * *"],
  description: '',
  columns: {}
}

SELECT
  tipo_assinante,
  globo_id,
  id_asset
from
  ${ref('usuarios', 'perfil_assinantes_ativo_reduzido')}